models/Students.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/31/2018
 * Time: 00:05
 */

namespace app\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{students}}".
 *
 * The followings are the available columns in table '{{students}}':
 * @property int $id
 * @property string $firstname
 * @property string $lastname
 * @property string $middlename
 * @property int $group_id
 */

class Students extends ActiveRecord
{

    public function attributes()
    {
        return [
            'id',
            'firstname',
            'lastname',
            'middlename',
            'group_id'
        ];
    }

    public function getGroups()
    {
        return $this->hasOne(Groups::class, ['id' => 'group_id']);
    }

    public function attributeLabels()
    {
        return [
            'firstname' => 'Имя',
            'lastname' => 'Фамилия',
            'middlename' => 'Отчество',
            'group_id' => 'Группа'
        ];
    }

    public function rules()
    {
        return [
            [['firstname', 'lastname', 'middlename', 'group_id'], 'required', 'message' => "Поле \"{attribute}\" не может быть пустым"],
        ];
    }

}

controllers/StudentsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/30/2018
 * Time: 23:32
 */

namespace app\controllers;

use app\models\Groups;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;
use app\models\Students;
use yii\web\NotFoundHttpException;

class StudentsController extends Controller
{
    /**
     * Displays page with student, related to groups
     *
     * @return string
     */
    public function actionIndex()
    {
        $query = Students::find()->with('groups');

        $pagination = new Pagination([
            'defaultPageSize' => 10,
            'totalCount' => $query->count()
        ]);

        $students = $query->joinWith('groups')
            ->orderBy('{{%groups}}.title')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'students' => $students,
            'pagination' => $pagination
        ]);
    }

    public function actionView($id)
    {
        $model = Students::find()->with('groups')->where(['id' => $id])->one();
        $groups = Groups::find()->all();

        if($model === null) {
            throw new NotFoundHttpException;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['students/index']);
        } else {
            return $this->render('view', [
                'model' => $model,
                'groups' => $groups
            ]);
        }
    }

    public function actionCreate()
    {
        $model = new Students();
        $groups = Groups::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['students/index']);
        } else {
            return $this->render('view', [
                'model' => $model,
                'groups' => $groups
            ]);
        }
    }

    public function actionDelete($id)
    {
        $model = Students::findOne($id);

        if($model === null) {
            throw new NotFoundHttpException;
        }

        if ($model->delete()) {
            return $this->redirect(['students/index']);
        }
    }

}

views/students/_item.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/31/2018
 * Time: 00:13
 */

use yii\helpers\Html;

echo '<tr>';
    echo '<td>' . Html::encode("{$data->lastname}") . ' ' . Html::encode("{$data->firstname}") . ' ' . Html::encode("{$data->middlename}") . '</td>';
    echo '<td>' . Html::encode("{$data->groups->title}") . '</td>';
    echo '<td>';
    echo Html::a('Ред.', ['/students/view/' . $data->id]) . ' ' . Html::a('Удал.', ['/students/delete/' . $data->id]);
    echo '</td>';
echo '</tr>';

views/students/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/30/2018
 * Time: 23:35
 */


/**
 * @var $this \app\controllers\StudentsController
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;

$this->title = 'Студенты';
?>

<div class="site-index">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-10">
                <h2>
                <small><?= Html::a('Группы', ['/groups']) ?> :: </small>
                <?= Html::encode($this->title) ?>
                </h2>
                <div class="col-lg-1 col-lg-offset-10">
                    <?= Html::a('Добавить студента', ['/students/create'], ['class' => 'btn btn-primary']) ?>
                </div>
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th scope="col" colspan="1">ФИО</th>
                            <th scope="col" colspan="2">Группа</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($students as $s) {
                        echo $this->render('_item', array('data' => $s));
                    }?>
                    </tbody>
                </table>
                <?= LinkPager::widget(['pagination' => $pagination]) ?>
            </div>
        </div>
    </div>
</div>

views/students/view.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/31/2018
 * Time: 01:18
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \yii\helpers\ArrayHelper;

($model->isNewRecord) ? $this->title = 'Добавление студента' : $this->title = 'Редактирование студента';
?>

<div class="site-index">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-5">
                <h2><?= Html::encode($this->title) ?></h2>
                <?php $form = ActiveForm::begin(); ?>
                <?= $form->field($model, 'lastname') ?>
                <?= $form->field($model, 'firstname') ?>
                <?= $form->field($model, 'middlename') ?>
                <?= $form->field($model, 'group_id')
                    ->dropDownList(ArrayHelper::map($groups, 'id', 'title')) ?>
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Отмена', ['/students/index'], ['class' => 'btn btn-default']) ?>
                <?php if(!$model->isNewRecord) { echo Html::a('Удалить', ['/students/delete/' . $model->id], ['class' => 'btn btn-danger']);} ?>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>