models/Groups.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/31/2018
 * Time: 00:05
 */

namespace app\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{groups}}".
 *
 * The followings are the available columns in table '{{groups}}':
 * @property int $id
 * @property string $title
 */

class Groups extends ActiveRecord
{

    public function attributes()
    {
        return [
            'id',
            'title'
        ];
    }

    public function getStudents()
    {
        return $this->hasMany(Students::class, ['group_id' => 'id']);
    }

    public function attributeLabels()
    {
        return [
            'title' => 'Номер группы'
        ];
    }

    public function beforeDelete()
    {
        Students::updateAll(['group_id' => ''], 'group_id = :id', [':id' => $this->id]);

        return parent::beforeDelete();
    }

    public function rules()
    {
        return [
            ['title', 'required', 'message' => 'Номер группы не может быть пустым'],
            ['title', 'unique', 'message' => "Номер группы \"{value}\" уже существует"],
        ];
    }

}

controllers/GroupsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/30/2018
 * Time: 23:32
 */

namespace app\controllers;

use Yii;
use yii\data\Pagination;
use yii\web\Controller;
use app\models\Groups;
use yii\web\NotFoundHttpException;

class GroupsController extends Controller
{
    /**
     * Displays page with groups, it also uses as home page
     *
     * @return string
     */
    public function actionIndex()
    {
        $query = Groups::find();

        $pagination = new Pagination([
            'defaultPageSize' => 10,
            'totalCount' => $query->count()
        ]);

        $groups = $query->orderBy('title')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'groups' => $groups,
            'pagination' => $pagination
        ]);
    }

    public function actionView($id)
    {
        $model = Groups::findOne($id);

        if($model === null) {
            throw new NotFoundHttpException;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['groups/index']);
        } else {
            return $this->render('view', [
                'model' => $model
            ]);
        }
    }

    public function actionCreate()
    {
        $model = new Groups;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['groups/index']);
        } else {
            return $this->render('view', [
                'model' => $model
            ]);
        }
    }

    public function actionDelete($id)
    {
        $model = Groups::findOne($id);

        if($model === null) {
            throw new NotFoundHttpException;
        }

        if ($model->delete()) {
            return $this->redirect(['groups/index']);
        }
    }

}

views/groups/_item.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/31/2018
 * Time: 00:13
 */

use yii\helpers\Html;

echo '<tr>';
    echo '<td>' . Html::encode("{$data->title}") . '</td>';
    echo '<td>';
    echo Html::a('Ред.', ['/groups/view/' . $data->id]) . ' ' . Html::a('Удал.', ['/groups/delete/' . $data->id]);
    echo '</td>';
echo '</tr>';

views/groups/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/30/2018
 * Time: 23:35
 */


/**
 * @var $this \app\controllers\GroupsController
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;

$this->title = 'Группы';
?>

<div class="site-index">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-10">
                <h2><?= Html::encode($this->title) ?>
                    <small> :: <?= Html::a('Студенты', ['/students']) ?></small>
                </h2>
                <div class="col-lg-1 col-lg-offset-10">
                    <?= Html::a('Добавить группу', ['/groups/create'], ['class' => 'btn btn-primary']) ?>
                </div>
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th scope="col" colspan="2">Группа</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($groups as $g) {
                        echo $this->render('_item', array('data' => $g));
                    }?>
                    </tbody>
                </table>
                <?= LinkPager::widget(['pagination' => $pagination]) ?>
            </div>
        </div>
    </div>
</div>

views/groups/view.php
<?php
/**
 * Created by PhpStorm.
 * User: Aleksey
 * Date: 10/31/2018
 * Time: 01:18
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

($model->isNewRecord) ? $this->title = 'Добавление группы' : $this->title = 'Редактирование группы';
?>

<div class="site-index">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-5">
                <h2><?= Html::encode($this->title) ?></h2>
                <?php $form = ActiveForm::begin(); ?>
                <?= $form->field($model, 'title') ?>
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Отмена', ['/groups/index'], ['class' => 'btn btn-default']) ?>
                <?php if(!$model->isNewRecord) { echo Html::a('Удалить', ['/groups/delete/' . $model->id], ['class' => 'btn btn-danger']);} ?>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>